package com.aimovie.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

@Entity
@Table(name = "subtitles")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Subtitle extends Auditable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "movie_id", nullable = false)
    @NotNull
    private Movie movie;

    @NotBlank
    @Size(max = 10)
    @Column(name = "language_code", length = 10, nullable = false)
    private String languageCode;

    @NotBlank
    @Size(max = 100)
    @Column(name = "language_name", length = 100, nullable = false)
    private String languageName;

    @Size(max = 1000)
    @Column(name = "subtitle_url", length = 1000)
    private String subtitleUrl;

    @Column(name = "is_default")
    @Builder.Default
    private Boolean isDefault = false;

    @Column(name = "is_auto_generated")
    @Builder.Default
    private Boolean isAutoGenerated = false;

    @Column(name = "file_size_bytes")
    private Long fileSizeBytes;

    @Column(name = "encoding", length = 50)
    @Builder.Default
    private String encoding = "UTF-8";

    @Column(name = "is_available")
    @Builder.Default
    private Boolean isAvailable = true;
}
