package com.aimovie.repository;

import com.aimovie.entity.Movie;
import com.aimovie.entity.Subtitle;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface SubtitleRepository extends JpaRepository<Subtitle, Long> {

    // Tìm tất cả phụ đề của một phim
    List<Subtitle> findByMovieAndIsAvailableTrueOrderByIsDefaultDescLanguageNameAsc(Movie movie);

    // Tìm phụ đề mặc định của một phim
    Optional<Subtitle> findByMovieAndIsDefaultTrueAndIsAvailableTrue(Movie movie);

    // Tìm phụ đề theo ngôn ngữ của một phim
    Optional<Subtitle> findByMovieAndLanguageCodeAndIsAvailableTrue(Movie movie, String languageCode);

    // Tìm phụ đề theo ID
    Optional<Subtitle> findByIdAndIsAvailableTrue(Long id);

    // Đếm số phụ đề của một phim
    long countByMovieAndIsAvailableTrue(Movie movie);

    // Tìm phụ đề theo ngôn ngữ
    List<Subtitle> findByLanguageCodeAndIsAvailableTrue(String languageCode);

    // Tìm phụ đề tự động tạo
    List<Subtitle> findByIsAutoGeneratedTrueAndIsAvailableTrue();

    // Tìm phụ đề theo encoding
    List<Subtitle> findByEncodingAndIsAvailableTrue(String encoding);

    // Cập nhật phụ đề mặc định
    @Query("UPDATE Subtitle s SET s.isDefault = false WHERE s.movie = :movie")
    void clearDefaultSubtitle(@Param("movie") Movie movie);

    // Tìm phụ đề có kích thước file lớn nhất
    @Query("SELECT s FROM Subtitle s WHERE s.movie = :movie AND s.isAvailable = true ORDER BY s.fileSizeBytes DESC")
    List<Subtitle> findByMovieOrderByFileSizeDesc(@Param("movie") Movie movie);

    // Tìm phụ đề theo ngôn ngữ và phim
    @Query("SELECT s FROM Subtitle s WHERE s.movie = :movie AND s.languageCode = :languageCode AND s.isAvailable = true")
    List<Subtitle> findByMovieAndLanguageCode(@Param("movie") Movie movie, @Param("languageCode") String languageCode);
    
    void deleteByMovie(Movie movie);
}
