package com.aimovie.dto;

import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SubtitleDTO {
    private Long id;
    private String language;
    private String languageName;
    private String languageCode;
    private String url;
    private String subtitleUrl;
    private String format; 
    private Boolean isDefault;
    private Boolean isAutoGenerated;
    private String encoding;
    private Long fileSizeBytes;
}
